version: "3.8"

services:
  db:
    image: "postgres"
    env_file: .env
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - db

  db_up:
    image: "amacneil/dbmate"
    env_file: .env
    environment:
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DATABASE?sslmode=disable
    restart: on-failure
    depends_on:
      - db
    command: up
    volumes:
      - ./db/:/db
    networks:
      - db

  duckling:
    image: ghcr.io/simmsb/duckling:latest
    restart: always
    networks:
      - duckling

  prometheus:
    image: "prom/prometheus"
    restart: always
    ports:
      - 127.0.0.1:9090:9090
    networks:
      - prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus

  bot:
    image: ghcr.io/simmsb/calamity-bot:latest
    restart: always
    depends_on:
      - db_up
      - db
    env_file: .env
    environment:
      - DB_STRING=host=db port=5432 user=$POSTGRES_USER dbname=$POSTGRES_DATABASE password=$POSTGRES_PASSWORD
    volumes:
      - ./assets:/assets
    networks:
      - db
      - duckling
      - prometheus

volumes:
  db-data:
  prometheus:

networks:
  db:
  duckling:
  prometheus:
