name:                calamity-bot
version:             0.0.0
github:              "nitros12/calamity-bot"
homepage:            https://github.com/nitros12/calamity-bot
bug-reports:         https://github.com/nitros12/calamity-bot/issues
license:             MIT
license-file:        LICENSE
author:              "Ben Simms"
maintainer:          "ben@bensimms.moe"
copyright:           2019 Ben Simms
category:            Bots
build-type:          Simple
extra-doc-files:
  - README.md
  - CHANGELOG.md
tested-with:         GHC == 8.8.2


synopsis:            A discord bot
description:         A discord bot


dependencies:
  - name: base
    version: ">= 4.12 && < 5"
    mixin:
      - hiding (Prelude)
  - name: relude
    mixin:
      - (Relude as Prelude, Relude.Unsafe, Relude, Relude.Extra)
  - calamity
  - di
  - di-core
  - di-polysemy
  - df1
  - polysemy
  - polysemy-plugin >= 0.2
  - lens
  - generic-lens
  - text
  - text-show
  - unordered-containers
  - beam-core
  - beam-postgres
  - arbor-lru-cache
  - bytestring
  - time
  - hourglass
  - megaparsec
  - table-layout
  - postgresql-simple
  - resource-pool
  - immortal
  - reanimate
  - reanimate-svg
  - process
  - filepath
  - data-default-class
  - emojis
  - JuicyPixels
  - linear
  - mime-types
  - wreq
  - process-extras
  - directory
  - temporary
  - pretty-simple
  - duckling

executables:
  calamity-bot:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -O2
      - -fspecialise-aggressively
      - -flate-specialise
      - -fplugin=Polysemy.Plugin
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wincomplete-uni-patterns
      - -Wincomplete-record-updates
      - -Wcompat
      - -Widentities
      - -Wredundant-constraints
      - -fhide-source-paths
      - -Wmissing-export-lists
      - -Wpartial-fields
      - -fno-warn-unused-do-bind
      - -eventlog
    dependencies:
      - calamity-bot
      - optparse-applicative

library:
  ghc-options:
    - -fplugin=Polysemy.Plugin
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wcompat
    - -Widentities
    - -Wredundant-constraints
    - -fhide-source-paths
    - -Wmissing-export-lists
    - -Wpartial-fields
    - -fno-warn-unused-do-bind
  source-dirs: src

default-extensions:
  - StrictData
  - IncoherentInstances
  - TemplateHaskell
  - RecursiveDo
  - AllowAmbiguousTypes
  - BlockArguments
  - NoMonomorphismRestriction
  - BangPatterns
  - BinaryLiterals
  - UndecidableInstances
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - DerivingVia
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  - DeriveAnyClass
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - OverloadedLabels
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns
  - DuplicateRecordFields
  - TypeOperators
  - TypeApplications
  - RoleAnnotations
  - PatternSynonyms
